import { OverlayWindow } from "overlay.slint";
import { PinWindow } from "pin.slint";
import { AiResultWindow } from "ai-result.slint";
import { EditorWindow } from "editor.slint";
import { LongshotWindow } from "longshot.slint";
import { SettingsWindow } from "settings.slint";
import { UpdateWindow } from "update.slint";

export {
    OverlayWindow,
    PinWindow,
    AiResultWindow,
    EditorWindow,
    LongshotWindow,
    SettingsWindow,
    UpdateWindow,
}
